import posthog from "posthog-js";
import {
  OUTBOUND_CLICKED, SCROLL_DEPTH, READ_COMPLETED, INTERNAL_LINK_CLICKED,
  PROP_SITE_SLUG, PROP_NICHE, PROP_OUTBOUND_DOMAIN, PROP_OUTBOUND_URL,
  PROP_DEPTH_PCT, PROP_ENGAGED_SECONDS, PROP_LINK_REGION,
  REGION_BODY, REGION_NAV, REGION_FOOTER, REGION_SIDEBAR,
  DEPTH_THRESHOLDS, READ_MIN_SECONDS,
} from "./content-schema.js";
import { regionOf } from "./shared-schema.js";


export { posthog };
